### ISSUE TITLE
Is the script still working?

### ISSUE THREAD

**Issue by Hatzen** [alexsomai/stackoverflow-fanatic-badge#16]
Looking into the code the python script is just simply logging into stackoverflow. But as mentioned here:  
https://meta.stackoverflow.com/a/298532/8524651  
A simple Login wont work (anymore?)

**Comment by alexsomai** [comment]
Actually the description is simplified. The script will also click on your profile (top right corner) and verify that the display name matches the one set in env vars (https://github.com/alexsomai/stackoverflow-fanatic-badge/blob/master/stack_overflow_page.py#L45).

Maybe I should add this statement in the README to make things more clear 🤔

**Comment by alexsomai** [comment]
I've updated the README to include that information, as well: https://github.com/alexsomai/stackoverflow-fanatic-badge/commit/a5935e8dc3a4c1af533f4665cc332cdbe5c0ddc1
