### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by SCcagg5** [alexsomai/stackoverflow-fanatic-badge#18]
Missing letter P in readme.md

Mandatory (basic login script variables):

* `STACK_OVERFLOW_EMAIL`
* `STACK_OVERFLOW_PASSWORD`
* `STACK_OVERFLOW_DISLAY_NAME`

STACK_OVERFLOW_DISPLAY_NAME

**Comment by alexsomai** [comment]
🤦‍♂️ Good catch, thanks! I've fixed it.
