### ISSUE TITLE
Use proper logging library instead of `print()` function

### ISSUE THREAD

**Issue by alexsomai** [alexsomai/stackoverflow-fanatic-badge#6]
Replace the use of `print()` function with proper logging, using a library, e.g., https://realpython.com/python-logging/ (or could be something else).

**Comment by aryaanlambe** [comment]
Hello!
May I be assigned this issue? Are there any deadlines I'm supposed to meet?

**Comment by alexsomai** [comment]
Hi! Thank you for your interest, I've assigned you. Nope, no deadlines, when you have the time :)
Please let me know if you have any questions or need clarifications.

**Comment by aryaanlambe** [comment]
Sure, will do!
I'll begin working on the issue soon :smile:

**Comment by alexsomai** [comment]
Done in #9. Thank you, @aryaanlambe
